### PR TITLE
Adding support for Zoom API v2

### PR DESCRIPTION
**Pull request by tomasgarzon**

### CODE REVIEW

**Comment by tarkatronic** [comment]
@prschmid Is this something you would still be interested in getting merged, if I were to pick up development where it was left off?

**Comment by prschmid** [comment]
@tarkatronic Yes! would love to get this merged if you were to make the requested changes. Thanks a lot!

**Comment by tarkatronic** [comment]
Great! I will try to get to this as soon as I have an opportunity.

**Comment by prschmid** [comment]
Closing this PR since all the work was taken over in PR #11  and merge in with commit https://github.com/actmd/zoomus/commit/b1c7c3a08dcf88ec1f5e443c669bf8b50b700df9

**Pull request closed without merging**
